### ISSUE TITLE
Content & Newsportlet nicht auf gleicher Höhe

### ISSUE THREAD

**Issue by mtokmak** [4teamwork/securityligue.web#2]
Der Content-Bereich und das Newsportlet auf der rechten Seite sind nicht auf gleicher Höhe, was das Aussehen verschlechtert.

Siehe Screenshot:
![bildschirmfoto 2016-04-11 um 16 21 26](https://cloud.githubusercontent.com/assets/2045638/14430429/e0f27aa0-0001-11e6-9f5c-5c93dd2b3c89.png)

**Comment by mtokmak** [comment]
Kannst du die Höhe nicht exakter einstellen? Siehe Screenshot:

![bildschirmfoto 2016-04-14 um 09 07 37](https://cloud.githubusercontent.com/assets/2045638/14519693/cdd5f3fe-0220-11e6-8958-c5d42732adb0.png)

**Comment by bierik** [comment]
Murat du bist einfach zu schnell :wink: 

<img width="947" alt="bildschirmfoto 2016-04-14 um 09 20 20" src="https://cloud.githubusercontent.com/assets/1637820/14519955/2e330e5c-0222-11e6-89a5-ab34cc5cf6d5.png">
